config/routes.rb
Rails.application.routes.draw do
  root to: 'authors/posts#index'
  devise_for :authors
  get "/healthtest", to: proc { [200, {}, ["ok"]] }

  scope module: 'authors' do
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  validates :email, presence: true, uniqueness: { case_sensitive: false }

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author

  validates :titre, presence: true
  validates :description, presence: true
  validates :published, exclusion: [nil]
  validates :published_at, presence: true
  validates :author, presence: true

  validates :categories, inclusion: { in: %w(dev ops tech business game),
                                      message: "%{value} is not a valid categorie" }

  def published_decorated
    published ? "Publié le #{published_at}" : 'Non publié'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def after_sign_out_path_for(resource_or_scope)
    new_author_session_path
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[ show edit update destroy ]

    # GET /posts or /posts.json
    def index
      @posts = Post.all
    end

    # GET /posts/1 or /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts or /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:titre, :description, :published, :published_at, :categories, :author_id)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :titre %>
  <%= f.input :description %>
  <%= f.input :published %>
  <%= f.input :published_at %>
  <%= f.hidden_field :author_id, value: current_author.id %>
  <%= f.input :categories, collection: %w(dev ops tech business game) %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/authors/posts/_navigator.html.erb
<div class='mt-5'>
  <%= link_to action_name, action, class: 'btn btn-info'%>
  <%= link_to 'Back', posts_path, class: 'btn btn-info'%>
</div>

app/views/authors/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= render partial: 'navigator', locals: { action_name: 'Show', action: @post} %>

app/views/authors/posts/index.html.erb
<h4 class='d-flex justify-content-between'>
  <span>Liste des posts</span>
  <%= link_to 'Créer un Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to post, class: 'text-decoration-none' do %>
    <div class='card mb-3'>
      <div class='card-body mb-1'>
        <h5 class='card-title text-dark'>
        <%= post.titre %>
        </h5>
        <p class='text-dark mb-0'>
          <%= post.published_decorated %>
        </p>
        <p class='text-secondary mt-3'>
          <%= post.description %>
        </p>
        <p class='text-secondary mt-3'>
          <%= post.categories %>
        </p>
      </div>
    </div>
  <%end%>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-info mt-5' %>

app/views/authors/posts/show.html.erb
<p>
  <strong>Titre:</strong>
  <%= @post.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published_decorated %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<p>
  <strong>Catégories :</strong>
  <%= @post.categories %>
</p>

<%= link_to 'Supprimer', @post, method: :delete, class: 'btn btn-danger' %>

<%= render partial: 'navigator', locals: { action_name: 'Editer', action: edit_post_path(@post) } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class='mr-auto'>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <img src="https://www.epitech.eu/digital/wp-content/uploads/2020/01/EPI-LOGO-DIGITAL-2019-BLANC.png" width="80" height="30" alt="">
        <% end %>
      </div>
      <form class="form-inline my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <div class="ml-auto">
        <ul class="navbar-nav">
          <% if author_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Déconnection', destroy_author_session_path, method: :delete, class: 'nav-link'%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Connextion', new_author_session_path, class: 'nav-link'%>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="notice alert alert-info mt-5"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert alert-danger mt-5"><%= alert %></p>
      <% end %>
      <div class='mt-5'>
        <%= yield %>
      </div>
    <div>
  </body>
</html>